---
- name: tap homebrew/cask-versions
  homebrew_tap: tap=homebrew/cask-versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - git-flow
    - wget
    - pwgen
    - rbenv
    - ruby-build
    - rbenv-gemset
    - nvm
    - postgresql
    - v8
    - kubectl

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - rubymine
    - visual-studio-code
    - brave-browser
    - google-chrome
    - firefox
    - spotify
    - istat-menus
    - spectacle
    - karabiner-elements
    - dash
    - flux
    - alfred
    - sketch
    - handbrake
    - adobe-creative-cloud
    - dropbox
    - bitwarden
    - whatsapp
    - grammarly
