---

- name: tap caskroom/versions
  homebrew_tap: tap=caskroom/versions state=present

- name: install developer brew applications
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras
    - git-flow
    - wget
    - pwgen
    - siege
    - watch
    - rsync
    - rbenv
    - ruby-build
    - rbenv-gemset
    - nvm
    - imagemagick
    - postgresql
    - mongodb
    - v8
    - qt

- name: install developer cask applications
  homebrew_cask: name={{item}} state=present
  with_items:
    - rubymine
    - intellij-idea
    - sourcetree
    - imageoptim
    - imagealpha
    - vlc
    - java
    - skype
    - google-chrome
    - firefox
    - spotify
    - istat-menus
    - spectacle
    - karabiner
    - dash
    - flux
    - launchbar
    - sketch
    - handbrake
    - utorrent
    - adobe-creative-cloud
    - microsoft-office
    - dropbox
    - sourcetree
    - slack
    - lastpass
    - virtualbox
    - google-drive
    - github-desktop
    - filezilla
    - robomongo